builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X "github.com/blinkdisk/core/repo.BuildVersion={{.Version}}" -X "github.com/blinkdisk/core/repo.BuildInfo={{.Commit}}" -X "github.com/blinkdisk/core/repo.BuildGitHubRepo={{.Env.GITHUB_REPOSITORY}}"
release:
  draft: false
snapshot:
  name_template: "{{ .Env.BLINKDISK_VERSION_NO_PREFIX }}"
